### ISSUE TITLE
Add support for Decimal data type to TSql syntax in Paramol

### ISSUE THREAD

**Issue by yreynhout** [yreynhout/Projac#21]

**Comment by ritasker** [comment]
Am I ok to pick this up?

**Comment by yreynhout** [comment]
Sure, go ahead. If you need any help, hit me up on gitter/twitter/slack. Copy the style of testing from Money. I prefer value objects for precision and scale. Add to SqlClientSyntax, not TSql.

**Comment by yreynhout** [comment]
Landed as v.0.0.147 on nuget and e53bfaaf05ba159cf9342e7699ef61c40172401b
